name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main   # troca se não for o seu branch principal

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration production --base-href /Eletrogil_angular/

      - name: Deploy with angular-cli-ghpages
        run: npx angular-cli-ghpages --dir=dist/EletroGil/browser --name "github-actions[bot]" --email "github-actions[bot]@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
