name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main   # ou o branch que você usa

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration production --base-href /Eletrogil_angular/

      - name: Deploy with angular-cli-ghpages
        run: npx angular-cli-ghpages --dir=dist/EletroGil/browser --no-silent --base-href /Eletrogil_angular/
