name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main   # troca se o branch principal do repo não for "main"

permissions:
  contents: write   # necessário para poder publicar no branch gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20   # pode trocar para a versão que você usa no projeto

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: ng build --prod --base-href "https://vhrm.github.io/Eletrogil_angular/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/EletroGil/browser

